HomeTask.LibraryProject/Models/AddBookViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeTask.LibraryProject.Models
{
    public class AddBookViewModel
    {
        public string BookName { get; set; }
        public string BookTitle { get; set; }
        public int BookYear { get; set; }
        public int AuthorId { get; set; }
        public string BookImageUrl { get; set; }
    }
}

HomeTask.LibraryProject/Models/AllBookViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeTask.LibraryProject.Models
{
    public class AllBookViewModel
    {
        public int BookId { get; set; }
        public string BookName { get; set; }
        public string BookTitle { get; set; }
        public string AuthorName { get; set; }
        public int ViewedCount { get; set; }
        public string ImageUrl { get; set; }

    }
}

HomeTask.LibraryProject/Models/AuthorBookCountViewModel.cs
using HomeTask.LibraryProject.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeTask.LibraryProject.Models
{
    public class AuthorBookCountViewModel
    {
        public string AuthorName { get; set; }
        public int BookCount { get; set; }
        public List<Book> Books { get; set; }
    }
}

HomeTask.LibraryProject/Models/BookDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeTask.LibraryProject.Models
{
    public class BookDetailViewModel
    {
        public string BookName { get; set; }
        public string BookTitle { get; set; }
        public int ViewedCount { get; set; }
        public string ImageUrl { get; set; }
        public string AuthorName { get; set; }

    }
}

HomeTask.LibraryProject/Models/ErrorViewModel.cs
using System;

namespace HomeTask.LibraryProject.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HomeTask.LibraryProject/Controllers/BookController.cs
using HomeTask.LibraryProject.Entity;
using HomeTask.LibraryProject.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace HomeTask.LibraryProject.Controllers
{
    public class BookController : Controller
    {
        private readonly DataContext context;

        public BookController(DataContext context)
        {
            this.context = context;
        }


        public IActionResult Index()
        {
            var data = context.Books
                .Include(i => i.Author)
                .Select(i => new AllBookViewModel
                {
                    BookId = i.Id,
                    BookName = i.Name,
                    BookTitle = i.Title,
                    AuthorName = i.Author.AuthorName,
                    ImageUrl = i.ImageUrl,
                    ViewedCount = i.ViewCount
                })
                .OrderByDescending(i => i.ViewedCount)
                .ToList();
            return View(data);
        }

        public IActionResult Detail(int id)
        {
            var book = context.Books.FirstOrDefault(i => i.Id == id);

            book.ViewCount = book.ViewCount + 1;
            context.SaveChanges();

            BookDetailViewModel data = new BookDetailViewModel()
            {
                BookName = book.Name,
                BookTitle = book.Title,
                ImageUrl = book.ImageUrl,
                ViewedCount = book.ViewCount,
                //AuthorName=book.Author.AuthorName
            };


            var entity = context.Books
                .Include(i => i.Author)
                .Where(i => i.Id == id)
                .Select(i => new BookDetailViewModel
                {
                    BookName = i.Name,
                    BookTitle = i.Title,
                    ImageUrl = i.ImageUrl,
                    ViewedCount = i.ViewCount,
                    AuthorName = i.Author.AuthorName
                }).FirstOrDefault();

            return View(entity);
        }

        public IActionResult AddBook()
        {

            ViewBag.Authors = new SelectList(context.Authors, "Id", "AuthorName");
            return View();
        }

        [HttpPost]
        public IActionResult AddBook(AddBookViewModel model, IFormFile file)
        {
            if (ModelState.IsValid)
            {

                if (file != null)
                {

                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", file.FileName);

                    using (var fs = new FileStream(path, FileMode.Create))
                    {
                        file.CopyTo(fs);
                        model.BookImageUrl = file.FileName;
                    }

                }


                Book b = new Book()
                {
                    Name = model.BookName,
                    AuthorId = model.AuthorId,
                    Title = model.BookTitle,
                    ImageUrl = model.BookImageUrl

                };

                context.Books.Add(b);
                context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            ViewBag.Authors = new SelectList(context.Authors, "Id", "AuthorName");

            return View(model);
        }

    }
}

HomeTask.LibraryProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HomeTask.LibraryProject.Models;

namespace HomeTask.LibraryProject.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HomeTask.LibraryProject/ViewComponents/BestBooksAuthorViewComponent.cs
using HomeTask.LibraryProject.Entity;
using HomeTask.LibraryProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeTask.LibraryProject.ViewComponents
{
    public class BestBooksAuthorViewComponent : ViewComponent
    {
        private readonly DataContext context;

        public BestBooksAuthorViewComponent(DataContext context)
        {
            this.context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var entity = context.Books
                .Include(i => i.Author)
                .ThenInclude(i=>i.Books)
                .Select(i => new AuthorBookCountViewModel()
                {
                    AuthorName = i.Author.AuthorName,
                    BookCount = i.Author.Books.Count(),
                    Books = i.Author.Books.ToList()
                })
                .OrderByDescending(i => i.BookCount)
                .FirstOrDefault();

            return View(entity);
        }

    }
}

HomeTask.LibraryProject/ViewComponents/BestSellerViewComponent.cs
using HomeTask.LibraryProject.Entity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeTask.LibraryProject.ViewComponents
{
    public class BestSellerViewComponent:ViewComponent
    {
        private readonly DataContext context;

        public BestSellerViewComponent(DataContext context)
        {
            this.context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {

            var data = context.Books
                .OrderByDescending(i => i.ViewCount)
                .FirstOrDefault();
            return View("Default",data);
        }
    }
}

HomeTask.LibraryProject/Views/Book/AddBook.cshtml
@model AddBookViewModel
@{
    ViewData["Title"] = "AddBook";
}

<h1>AddBook</h1>

<form asp-action="AddBook" asp-controller="Book" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="BookName">Book Name</label>
        <input type="text" class="form-control" asp-for="BookName">
        <span asp-validation-for="BookName"></span>
    </div>

    <div class="form-group">
        <label asp-for="BookTitle">Book Title</label>
        <input type="text" class="form-control" asp-for="BookTitle">
        <span asp-validation-for="BookTitle"></span>
    </div>

    <div class="form-group">
        <label asp-for="AuthorId">Author Name</label>
        <select class="form-control" asp-for="AuthorId" asp-items="ViewBag.Authors">
            
        </select>

    </div>

    <div class="form-group">
        <label for="file">File input</label>
        <input type="file" class="form-control-file" id="file" name="file">
    </div>
    <div class="form-group">
        <input type="submit"  value="Add Book" class="form-control" />
    </div>

</form>

HomeTask.LibraryProject/Views/Book/Detail.cshtml
@model BookDetailViewModel
@{
    ViewData["Title"] = "Detail";
}

<h1>Detail</h1>

<div class="card mb-3">
    <img src="~/images/@Model.ImageUrl" class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">@Model.BookName</h5>
        <p class="card-text">@Model.BookTitle.</p>
        <p class="card-text">@Model.AuthorName</p>
        <p class="card-text"><small class="text-muted">@Model.ViewedCount</small></p>
    </div>
</div>

HomeTask.LibraryProject/Views/Book/Index.cshtml
@model IEnumerable<AllBookViewModel>
@{
    ViewData["Title"] = "Index";
}

<h1>@await Component.InvokeAsync("BestBooksAuthor")</h1>


<div class="container-fluid ">
    <div class="row ">
        
        <div class="col-md-4">
            <div class="row">
        @foreach (var item in Model)
        {
            <div class="card" style="width: 18rem;">
                <img src="~/images/@item.ImageUrl" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">@item.BookName</h5>
                    <p class="card-text">@item.BookTitle</p>
                    <p class="card-text">@item.ViewedCount</p>
                    <p class="card-text">@item.AuthorName</p>
                    <a asp-action="Detail" asp-controller="Book" asp-route-id="@item.BookId" class="btn btn-primary">All Information for this book</a>
                </div>
            </div>
        }

            </div>
        </div>
        <div class="col-md-6">
            <div class="col-md-4">
                @await Component.InvokeAsync("BestSeller")
            </div>
        </div>
    </div>
</div>

HomeTask.LibraryProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HomeTask.LibraryProject/Views/Shared/Components/BestBooksAuthor/Default.cshtml
@model AuthorBookCountViewModel
    <div class="card" style="width: 18rem;">
        
        <div class="card-body">
            <p class="card-text">@Model.AuthorName</p>
        </div>
    </div>


@foreach (var item in Model.Books)
{
<p>@item.Name</p>
}

HomeTask.LibraryProject/Views/Shared/Components/BestSeller/Default.cshtml
@model HomeTask.LibraryProject.Entity.Book


    <div class="card" style="width: 18rem;">
        <img src="~/images/@Model.ImageUrl" class="card-img-top" alt="...">
        <div class="card-body">
            <p class="card-text">The Best Seller Book: @Model.Name</p>
        </div>
    </div>

HomeTask.LibraryProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HomeTask.LibraryProject</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />

    <style>
        img{
            height:300px;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HomeTask.LibraryProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="AddBook">Add Book</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - HomeTask.LibraryProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>